language: java
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file:
    - target/parameterz-core-$project_version.jar
  skip_cleanup: true
  on:
    tags: true
  name: $project_version
  draft: true
